parameters:
#    blas_blog.example.class: Blas\BlogBundle\Example

services:
#    blas_blog.example:
#        class: %blas_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
